name: "Install dependencies"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v2

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: 18

    # use bash to create npmrc file for @rabbitholegg scope registry with auth token
    - name: Create npmrc file
      shell: bash
      run: |
        echo "@rabbitholegg:registry=//registry.npmjs.org/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts
